### ISSUE TITLE
M1 macs have problems with Swiftlint

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#158]
from @adamstener 

> On an M1 mac, you need to symlink your brew installed swiftlint over to the location where it would be if you had installed swiftlint with brew on a non-M1 mac. ` opt/homebrew/bin` -> `/usr/local/bin`

> If you symlink these locations for swiftlint and swiftgen, then we don't need to make any project modifications.

Things to do:

Add troubleshooting steps on the README section to explain this.

**Comment by LukasKorba** [comment]
Hi guys, let's break this down a bit.

## Apple Silicon and Homebrew swiftlint

Installing `swiftlint` via Homebrew:
```
brew install swiftlint
```
installs the latest version available. Currently `0.46.2`. On Apple Silicon chips the installation path differs from the Intel chips. More at [Homebrew doc](https://docs.brew.sh/Installation). The `swiftlint` ends up at `/opt/homebrew` instead of `/usr/local`. 

Therefore Xcode is not able to find `swiftlint` and there are 2 possible options how to fix it.

1. Add export PATH to the Build Phase run script:
```
# Adds support for Apple Silicon brew directory
export PATH="$PATH:/opt/homebrew/bin"
```

2. Symlink `swiftlint` 
```
sudo ln -s /opt/homebrew/bin/swiflint /usr/local/bin
```

It's up to discussion what do we prefer out of these two options. 

However both options are valid only when `brew install swiftlint` successfully finished! Since we force swiftlint to be at specific version 0.45.0:

```
swiftlint_version=0.45.0

if which swiftlint >/dev/null; then
  if [ $(swiftlint version) = $swiftlint_version ]; then
      swiftlint
  else
    echo "warning: Compatible SwiftLint version not installed, download version $swiftlint_version from https://github.com/realm/SwiftLint. Currently installed version is $(swiftlint version)"
  fi  
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```
following:
```
brew install swiftlint
```
fails and alternative:
```
brew install swiftlint@0.45.0 
```
doesn't work either. Apparently homebrew doesn't have 0.45.0 version available. I tried also 
```
brew search swiftlint
```
which supports there's really no 0.45.0 available. That forces newcomers to download 0.45.0 manually and copy paste it to `/usr/local/`. 

## Summary
In order to use either symlink or export PATH we need to rely on homebrew installation of latest 0.46.2 version. My proposal would be to upgrade our xcode run script to force swiftlint version 0.46.2. I briefly discussed with @pacu is there's a real reason why we cap it to 0.45.0 and seems like we should be fine with 0.46.2. 

I tested 0.46.2, I was able to build & run the project with no issues or any visible signs of breaking anything. 

As long as we insist to stay on 0.45.0, only the manual download and copy paste would work for Apple Silicon users.

**Comment by adamstener** [comment]
I would  suggest we update our docs to mention symlinking for those in this situation but ultimately note that swiftlint and swiftgen must be available on your PATH where Xcode can see them.  Modifying our build phase to cover a specific situation for a given CPU and installation method seems like it will cause unnecessary maintenance.

As far as updating, we should be able to update to any new version of swiftlint as long as it's tested and any modifications are made for new warnings or errors.  This one is very easy because there are none.

**Comment by LukasKorba** [comment]
In light of all feedback I've collected I suggest we add a new section to the readme file about Installation of the swiftlint and swiftgen on apple silicon chips. I'll use homebrew as a default way for the installation of both so we don't frame it as "in case you use homebrew, here's the troubleshooting" but rather "Installation of Swiftlint & Swiftgen on Apple Silicon"

objections?

**Comment by pacu** [comment]
Sounds good to me!
