### ISSUE TITLE
[Scaffold] Wallet Import Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#165]
Create the wallet import screen 
(just the ui elements)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/68051c09-f94c-4725-bb4b-53b46567d1f7)

**Comment by LukasKorba** [comment]
Final state of the task:

| dark | light |
| --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2022-03-01 at 10 45 59](https://user-images.githubusercontent.com/7198042/156145395-775c1ca5-689a-4e8e-82ca-5ab43b295511.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2022-03-01 at 10 45 39](https://user-images.githubusercontent.com/7198042/156145384-c5ea614c-6e18-4283-9f7a-7dadd67ee2c7.png) |

**Comment by LukasKorba** [comment]
# Known Issues
The onboarding flow is not wrapped in NavigationView and that caused ProgressView to be broken when entering the flow. The progress is transited from top of the screen to the bottom. Quick investigation on my side revealed that it may be connected to usage of .animated() (line 56, file: OnboardingProgressIndicator.swift). More details [here](https://developer.apple.com/forums/thread/682779)

I also tried to not rely on custom onboardingProgressStyle like this:
```swift
ProgressView(
                        String(format: "%02d", viewStore.index + 1),
                        value: Double(viewStore.index + 1),
                        total: Double(viewStore.steps.count)
                    )
                    //.onboardingProgressStyle
                    .padding(.horizontal, 30)
                    .padding(.vertical, 20)
                    .animation(.easeInOut)
```

The issue is still there. Removing .animation(easeInOut) hotfixes the issue but changed the animation of the progress bar to be linear. I consider it ok for the MVP, we can open an issue to investigate further but right now I want to deliver high priority tasks first.

**Comment by pacu** [comment]
@LukasKorba would you mind creating a new Issue with this known issue and make an explicit reference in the code with a // FIXME:  comment?

**Comment by LukasKorba** [comment]
> @LukasKorba would you mind creating a new Issue with this known issue and make an explicit reference in the code with a // FIXME: comment?

both done, https://github.com/zcash/secant-ios-wallet/issues/184
