### ISSUE TITLE
[Localization] Move Texts to Localizable File

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#174]
move the Texts present in the following features into a localizable strings file:
- Welcome Screen
- Onboarding Flow
- Secret Recovery Phrase Display
- Secret Recovery Phrase Validation + success and failed flows

out of scope:
- Recovery Phrases won't be localized they will be displayed in English.
- Placeholder screens.

**Comment by LukasKorba** [comment]
# Note
It's done and I used manual approach so it's under our control. 

The other option is to use `Xcode->Product->Export Localizations...` (and Import Localizations... after editorial transaltions) but this approach is not giving us any added value at the moment due to many placeholders. 

I also haven't added any comments to the Text() instances. It would mean extra work but there's only a very little added value. We have all strings under our control and we don't need to relay on external translators.

**Comment by LukasKorba** [comment]
merged
