### ISSUE TITLE
Onboarding Animation Broken

### ISSUE THREAD

**Issue by adamstener** [zcash/secant-ios-wallet#181]
![CleanShot 2022-02-28 at 06 05 44](https://user-images.githubusercontent.com/680770/155985355-353ff3db-2995-470e-996e-69e10eb92e5b.gif)

### Describe the issue
Please provide a general summary of the issue you're experiencing

The onboarding badge animation no longer animates the badge position.

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

The badge should animate to the new position along with the onboarding circle.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

- App Version: 
- iOS Version:
- Device: (if applies)

**Comment by LukasKorba** [comment]
After some investigation I've been able to identify what is causing the badge to be broken. 

Previously the badge images were defined:
```swift
var image: Image {
        switch self {
        case .shield: return Asset.Assets.Icons.shield.image
        case .list: return Asset.Assets.Icons.list.image
        case .person: return Asset.Assets.Icons.profile.image
        }
    }
```
somebody changed it to
```swift
 @ViewBuilder var image: some View {
        switch self {
        case .shield:
            Asset.Assets.Icons.shield.image
                .resizable()
                .renderingMode(.none)
        case .list:
            Asset.Assets.Icons.list.image
                .resizable()
                .renderingMode(.none)
        case .person:
            Asset.Assets.Icons.profile.image
                .resizable()
                .renderingMode(.none)
        case .error:
            ErrorBadge()
        }
    }
```
and that is the root cause of the issue. I'm pretty sure the issue was present even before onboarding enhancements task was done. At this point I don't know why it's broken as well as how to solve it other than getting back to previous version and setting 
```swift
.resizable()
.renderingMode(.none)
```
manually like before
